param(
    [string]$Action = "bundle"
)

$ErrorActionPreference = 'Continue'
$libDir = ".\lib"
$bundleFile = "$libDir\bundle.lib.js"
$reportFile = "$libDir\bundle-report.txt"

# Ensure lib directory exists
if (-not (Test-Path $libDir)) {
    New-Item -ItemType Directory -Path $libDir | Out-Null
}

function Write-Log {
    param([string]$Message, [string]$Level = "INFO")
    $timestamp = Get-Date -Format "HH:mm:ss"
    $output = "[$timestamp] [$Level] $Message"
    Write-Host $output
    return $output
}

function Get-AllLibraries {
    Get-ChildItem -Path "." -Filter "*.lib.js" -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Name
}

function Deduplicate-Libraries {
    Write-Log "Starting deduplication process..." "DEDUPE"
    
    $libs = @(Get-AllLibraries)
    $functions = @{}
    $duplicates = @()
    
    foreach ($lib in $libs) {
        $content = Get-Content -Path $lib -ErrorAction SilentlyContinue
        
        # Find all function declarations
        $funcMatches = [regex]::Matches($content, 'function\s+(\w+)\s*\(')
        
        foreach ($match in $funcMatches) {
            $funcName = $match.Groups[1].Value
            
            if ($functions.ContainsKey($funcName)) {
                $duplicates += @{
                    Function = $funcName
                    File1 = $functions[$funcName]
                    File2 = $lib
                }
                Write-Log "DUPLICATE: $funcName in $lib and $($functions[$funcName])" "WARN"
            } else {
                $functions[$funcName] = $lib
            }
        }
    }
    
    return $duplicates
}

function Bundle-Libraries {
    Write-Log "Bundling libraries into single file..." "BUNDLE"
    
    $libs = @(Get-AllLibraries)
    
    if ($libs.Count -eq 0) {
        Write-Log "No library files found to bundle" "WARN"
        return $false
    }
    
    $bundle = @"
// TEoAAAG Dashboard - Auto-Generated Library Bundle
// Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
// Library Count: $($libs.Count)
// DO NOT EDIT - Generated by lib-manager.ps1

`$bundleInfo = {
  generatedAt: new Date('$(Get-Date -Format 'o')'),
  version: '1.0.0',
  libCount: $($libs.Count),
  libraries: [$($libs | ForEach-Object { "'" + $_ + "'" } | Join-String -Separator ', ')]
};

"@
    
    foreach ($lib in $libs) {
        Write-Log "Including: $lib"
        $content = Get-Content -Path $lib -ErrorAction SilentlyContinue
        $bundle += "`n/* ===== $lib ===== */`n"
        $bundle += $content + "`n`n"
    }
    
    # Add bundle loader
    $bundle += @"

// Library Loader - Call libraries at start
console.log('[TEoAAAG] Library bundle loaded: ' + `$bundleInfo.libCount + ' libraries');
if (typeof window !== 'undefined') {
  window.TEoAAAG = window.TEoAAAG || {};
  window.TEoAAAG.libInfo = `$bundleInfo;
}

"@
    
    $bundle | Out-File -FilePath $bundleFile -Encoding UTF8 -Force
    $size = (Get-Item $bundleFile).Length
    Write-Log "Bundle created: $bundleFile ($size bytes)"
    
    return $true
}

function Inject-Into-HTML {
    Write-Log "Injecting library reference into index.html..."
    
    $htmlFile = ".\index.html"
    if (-not (Test-Path $htmlFile)) {
        Write-Log "ERROR: index.html not found" "ERROR"
        return $false
    }
    
    $html = Get-Content -Path $htmlFile -Raw -ErrorAction SilentlyContinue
    
    # Check if already injected
    if ($html -like '*bundle.lib.js*') {
        Write-Log "Library already referenced in index.html"
        return $true
    }
    
    # Find the last </script> tag before </body>
    $scriptTag = '<script src="./lib/bundle.lib.js"></script>'
    
    if ($html -like '*</body>*') {
        $html = $html -replace '(</body>)', "`n    $scriptTag`n`$1"
    } else {
        $html += "`n$scriptTag`n"
    }
    
    $html | Out-File -FilePath $htmlFile -Encoding UTF8 -Force
    Write-Log "Injected: <script src=\"./lib/bundle.lib.js\"></script>"
    
    return $true
}

function Validate-Dependencies {
    Write-Log "Validating dependencies..."
    
    $libs = @(Get-AllLibraries)
    $allFunctions = @{}
    $missingDeps = @()
    
    foreach ($lib in $libs) {
        $content = Get-Content -Path $lib -ErrorAction SilentlyContinue
        
        # Find function declarations
        $funcMatches = [regex]::Matches($content, 'function\s+(\w+)\s*\(')
        foreach ($match in $funcMatches) {
            $allFunctions[$match.Groups[1].Value] = $lib
        }
    }
    
    foreach ($lib in $libs) {
        $content = Get-Content -Path $lib -ErrorAction SilentlyContinue
        
        # Find function calls
        $callMatches = [regex]::Matches($content, '\b([a-zA-Z_]\w*)\s*\(')
        foreach ($match in $callMatches) {
            $funcName = $match.Groups[1].Value
            
            # Skip if it's a known function or built-in
            if (-not $allFunctions.ContainsKey($funcName) -and -not ($funcName -match '^(console|document|window|alert|setTimeout|fetch|JSON|Object|Array|Math|Promise|async|await)$')) {
                if ($missingDeps -notcontains $funcName) {
                    $missingDeps += $funcName
                    Write-Log "MISSING: Function '$funcName' not defined" "WARN"
                }
            }
        }
    }
    
    if ($missingDeps.Count -eq 0) {
        Write-Log "All dependencies validated successfully" "PASS"
    }
    
    return $missingDeps.Count
}

function Generate-Report {
    Write-Log "Generating bundle report..."
    
    $libs = @(Get-AllLibraries)
    $duplicates = Deduplicate-Libraries
    $missing = Validate-Dependencies
    
    $report = @"
================================================================================
                  TEoAAAG Dashboard Library Bundle Report
                        Generated: $(Get-Date)
================================================================================

SUMMARY
-------
Total Libraries:        $($libs.Count)
Library Files:          $(($libs | Measure-Object).Count)
Duplicate Functions:    $($duplicates.Count)
Missing Dependencies:   $missing

LIBRARIES
---------
$($libs | ForEach-Object { "  - $_" } | Out-String)

STATISTICS
----------
Bundle File:            $(if (Test-Path $bundleFile) { $true } else { $false })
Bundle Size:            $(if (Test-Path $bundleFile) { (Get-Item $bundleFile).Length } else { 'N/A' }) bytes
Last Updated:           $(if (Test-Path $bundleFile) { (Get-Item $bundleFile).LastWriteTime } else { 'Never' })

ISSUES FOUND
------------
$(@"
Duplicates:   $($duplicates.Count)
$($duplicates | ForEach-Object { "  - Function '$($_.Function)' in $($_.File1) and $($_.File2)" } | Out-String)

Missing:      $missing
"@)

RECOMMENDATIONS
---------------
1. Review and remove duplicate functions
2. Ensure all called functions are defined
3. Keep library files under 50KB each
4. Use descriptive names: name.lib.js
5. Run lib-manager auto every time you add new libraries

NEXT STEPS
----------
1. Run: lib-manager.bat auto
2. Check: lib-manager.bat check
3. Build: npm run build

================================================================================
"@
    
    $report | Out-File -FilePath $reportFile -Encoding UTF8 -Force
    Write-Host $report
    
    return $report
}

# Execute requested action
switch ($Action) {
    "deduplicate" { Deduplicate-Libraries | Out-Null }
    "bundle" { Bundle-Libraries | Out-Null }
    "inject" { Inject-Into-HTML | Out-Null }
    "report" { Generate-Report | Out-Null }
    "check" { Validate-Dependencies | Out-Null }
    "validate" { Validate-Dependencies | Out-Null }
    "fullreport" { Generate-Report | Out-Null }
    default { Write-Log "Unknown action: $Action" "ERROR" }
}

Write-Log "Operation complete"
